### ISSUE TITLE
Can't compile for ESP32 with 4MB flash

### ISSUE THREAD

**Issue by crstrand** [satrik/esp32_ble_inkbird#1]
First off, I LOVE your app.  Exactly what I was looking for.  However, I can't compile it under Arduino 1.8.13.
I'm sure it's a configuration required somewhere, but I don't know where that is.
I'm using a NodeMCU-32S clone with 4MB flash.
```
text section exceeds available space in boardSketch uses 1425414 bytes (108%) of program storage space. Maximum is 1310720 bytes.

Global variables use 53080 bytes (16%) of dynamic memory, leaving 274600 bytes for local variables. Maximum is 327680 bytes.
Sketch too big; see http://www.arduino.cc/en/Guide/Troubleshooting#size for tips on reducing it.
Error compiling for board NodeMCU-32S.

```

I know I shouldn't answer my own question, but I can't un-ring the bell.
My issue was, I was selecting the wrong board.  My clone is actually a Lolin32 clone.
When I select THAT board, I am given the `Tools->Partition Scheme` menu option from which I can select `Minimal SPIFFS`

**Comment by satrik** [comment]
@crstrand nice to hear that it works now. If you are facing issues with "memory leaks", try to use a `Partition Scheme` without `OTA`
