### ISSUE TITLE
HomeAssistant integration

### ISSUE THREAD

**Issue by trynqz** [satrik/esp32_ble_inkbird#3]
Hi, I managed to use your dev branch, it works great with my IBT-6x via ESP32 wroom-32U. I got all the probes accessible via WIFI and WWW. **Thanks for your great work.** 
Can you please advice, how I can integrate received data with homeAssistant? I would like to track probe values and make use of them doing further automations...like turn of the smoker heater if the set temperature value is reached.
This is my first Arduino and ESP32 tryouts, so sorry if this is low level question :)

**Comment by satrik** [comment]
hi @trynqz,
sorry I've absolutely no experience with HomeAssistant and I've never used it.
but if you access `/probes` of the esp, you get the "raw values" in JSON format and I think [this](https://www.home-assistant.io/integrations/rest/) integration could be what you need.

**Comment by trynqz** [comment]
HI, thanks for your comment. It was 100% accurate. I'm struggling little bit with converting 6552 to 0/off value. When I'll finish, I'll post the setup, maybe someone else will be interested. Still it works PERFECT, and gave me prety cool setup to automate the smoker :)

**Comment by trynqz** [comment]
Hi, so this is a big moment... for me :) it finally worked. Below I paste HomeAssistant config. In order to have nice statistisc graph  I'm converting 6552 value to 0. I use inkbird only when smoking hot, so value "0" means "off" for me, and it never happens in real life.

configuration.yaml
`
sensor:
# konfiguracja interfejsu do odczytu wskazań temperatury z termometru BT inkBird poprzez ESP32
  - platform: rest
    name: "meat_probe"
    resource: http://xx.xx.xx.xx/probes
    json_attributes:
      - "p1"
      - "p2"
      - "p3"
      - "p4"
      - "p5"
      - "p6"
    value_template: "OK"
  - platform: template
    sensors:
      probe1_temperature:
        value_template: >
          {% if state_attr('sensor.meat_probe', 'p1') == 6552.0 %}
          0
          {% else %}
          {{ state_attr('sensor.meat_probe', 'p1') }}
          {% endif %}
        icon_template: >
          {% if state_attr('sensor.meat_probe', 'p1') == 6552.0 %}
          mdi:thermometer-alert
          {% else %}
          mdi:thermometer
          {% endif %}
        device_class: temperature
        unit_of_measurement: "°C"
      probe2_temperature:
        value_template: >
          {% if state_attr('sensor.meat_probe', 'p2') == 6552.0 %}
          0
          {% else %}
          {{ state_attr('sensor.meat_probe', 'p2') }}
          {% endif %}
        icon_template: >
          {% if state_attr('sensor.meat_probe', 'p2') == 6552.0 %}
          mdi:thermometer-alert
          {% else %}
          mdi:thermometer
          {% endif %}
        device_class: temperature
        unit_of_measurement: "°C"
      probe3_temperature:
        value_template: >
          {% if state_attr('sensor.meat_probe', 'p3') == 6552.0 %}
          0
          {% else %}
          {{ state_attr('sensor.meat_probe', 'p3') }}
          {% endif %}
        icon_template: >
          {% if state_attr('sensor.meat_probe', 'p3') == 6552.0 %}
          mdi:thermometer-alert
          {% else %}
          mdi:thermometer
          {% endif %}
        device_class: temperature
        unit_of_measurement: "°C"
      probe4_temperature:
        value_template: >
          {% if state_attr('sensor.meat_probe', 'p4') == 6552.0 %}
          0
          {% else %}
          {{ state_attr('sensor.meat_probe', 'p4') }}
          {% endif %}
        icon_template: >
          {% if state_attr('sensor.meat_probe', 'p4') == 6552.0 %}
          mdi:thermometer-alert
          {% else %}
          mdi:thermometer
          {% endif %}
        device_class: temperature
        unit_of_measurement: "°C"
      probe5_temperature:
        value_template: >
          {% if state_attr('sensor.meat_probe', 'p5') == 6552.0 %}
          0
          {% else %}
          {{ state_attr('sensor.meat_probe', 'p5') }}
          {% endif %}
        icon_template: >
          {% if state_attr('sensor.meat_probe', 'p5') == 6552.0 %}
          mdi:thermometer-alert
          {% else %}
          mdi:thermometer
          {% endif %}
        device_class: temperature
        unit_of_measurement: "°C"
      probe6_temperature:
        value_template: >
          {% if is_state_attr('sensor.meat_probe', 'p6', 6552.0) %}
            0
          {% else %}
            {{ state_attr('sensor.meat_probe', 'p6') }}
          {% endif %}
        icon_template: >
          {% if is_state_attr('sensor.meat_probe', 'p6', 6552.0) %}
          mdi:thermometer-alert
          {% else %}
          mdi:thermometer
          {% endif %}
        device_class: temperature
        unit_of_measurement: "°C"
`

Lovelace code:

`
type: horizontal-stack
cards:
  - type: vertical-stack
    cards:
      - type: entities
        entities:
          - entity: switch.sonoff_10005bb0fc
            secondary_info: last-changed
            icon: mdi:grill-outline
          - entity: sensor.sonoff_10005bb0fc_temperature
            secondary_info: last-changed
        show_header_toggle: false
        title: BBQ
      - type: history-graph
        entities:
          - entity: sensor.sonoff_10005bb0fc_temperature
        hours_to_show: 10
  - type: thermostat
    entity: climate.booxasmooker_termostat
  - type: vertical-stack
    cards:
      - type: entities
        entities:
          - entity: sensor.probe1_temperature
          - entity: sensor.probe2_temperature
          - entity: sensor.probe3_temperature
          - entity: sensor.probe4_temperature
          - entity: sensor.probe5_temperature
          - entity: sensor.probe6_temperature
      - type: history-graph
        entities:
          - entity: sensor.probe1_temperature
            name: szynka_nisko
          - entity: sensor.probe2_temperature
            name: szynka_wysoko
          - entity: sensor.probe3_temperature
            name: schab_nisko
          - entity: sensor.probe4_temperature
            name: schab_wysoko
          - entity: sensor.probe5_temperature
          - entity: sensor.probe6_temperature
        hours_to_show: 10
        refresh_interval: 0

`

![obraz](https://user-images.githubusercontent.com/76698120/142772725-45f1b968-73a2-4a61-9724-717c8c6bd8a8.png)

**Comment by trynqz** [comment]
@satrik thanks for this integration!!

**Comment by satrik** [comment]
@trynqz looks really nice! 
You should check if you can parse the json and generate the templates dynamically according to the number of probes provided by the esp. I think there should be something like a `foreach` or `for in` loop which can do this. 
This would make it easier to use for other devices with more/less probes 🙂

**Comment by trynqz** [comment]
Thanks. One question, how do you handle inkbird battery state?
My observation is, that batteries like to die, not at the begining of
cooking, when there is time to prepare, but just about when the meat is
almost ready... It would be great to program some sort notification,
aspecially now when I do not need to use BBQ go app.
Regards
Rafał

śr., 24 lis 2021, 15:13 użytkownik satrik ***@***.***>
napisał:

**Comment by satrik** [comment]
the code don't handle it at all because it doesn't make sense for me to know the current state in percent. in my case it's quite simple, if the esp isn't reachable, i assume the battery is empty 😄

but if you need this feature, it shouldn't be hard to implement it yourself as there are a lot of other projects which use this feature.

**Comment by trynqz** [comment]
Not reachable = dead is best simple solution, but sometimes when I do beef
ribs and they stay in the smoker during the night, it would be great just
to prepare myself for battery change before I go to sleep.

I'm copy/paste hacker ... Not even close to be possible to do any
implementation myself. If you could in some future add it, maybe as an
addition to other implementation changes, I will be more than grateful. If
not - I will just changed batteries more often.


czw., 25 lis 2021, 12:01 użytkownik satrik ***@***.***>
napisał:
