### ISSUE TITLE
Meater + probe, how to connect

### ISSUE THREAD

**Issue by JensBecker68** [satrik/esp32_ble_inkbird#5]
Hello, 

I've downloaded the code and successfully installed on my esp32-s3. It is running, however not seeing my meater probe. 
Can you tell me which uuids I have to enter to find my probe. From what I can see in nrf scanner I have the following values:

Custom Service: a75cc7fc-c956-488f-ac2a-2dbc08b63a04

Characteristics: 7edda774-045e-4bbf-909b-45d1991a2876
At least the temperature values I can guess, as it changes, while I warm up the probe. 

Any hints,
Thanks

**Comment by satrik** [comment]
Hey, you can't just replace the UUIDs to make it work. The complete connection process is different and also the format is not the same like inkbirds.
Quick search shows me [this](https://github.com/nathanfaber/meaterble) project, maybe this is a good starting point.

**Comment by JensBecker68** [comment]
Thanks. Then I mixed up something. I thought this implementation can work with meater.

Thanks for the link
