### ISSUE TITLE
Doesn't work with Inkbird INT-11P-B

### ISSUE THREAD

**Issue by dabu667** [satrik/esp32_ble_inkbird#7]
Hello,

Is this supposed to work (or tested) with Inkbird INT-11P-B?
I tried several ESP32 cores - 1.0.6, 2.0.14 and 3.0.5 but the web interface doesn't get past the connecting animation. In the console I get the "right" message I guess:
_..... 
IP address: 192.168.0.180
MDNS: inkbird
Handle index
Handle data
Inkbird connected
Handle data
Handle data_

.. but then this error shows in browser:
![image](https://github.com/user-attachments/assets/9bbf42db-318d-4ae2-8e6c-7d89436b1806)

Do you have any advise for me?

**Comment by satrik** [comment]
hey there, when I've written this code, there were only the IBT series available and these are the only devices which should work with this code. just checked the description of the INT-11P-B and it works completely different as it uses the case as a repeater and it also uses another app the the older models. 
so Im sorry, but this project will not work with your device
